### ISSUE TITLE
L3 - Fix usage of json-server

### ISSUE THREAD

**Issue by lefduti** [arambazamba/ng-dev#199]
Wie in der Schulung geschrieben, habe ich nun den Fehler gefunden. Es gehört hier noch ergänzt, dass die 'environment.apiUrl' erweitert gehört um den richtigen Pfad. 
Also um `environment.apiUrl + "menu-items"` in `navbar.service.ts` und `${environment.apiUrl}food` in `food.service.ts`

https://github.com/arambazamba/ng-dev/blob/a5f6dcae9c7d54f3d010ca72a5b8dc6c3592c50c/labs/L3-routing/readme.md?plain=1#L66

**Comment by arambazamba** [comment]
Vielen Dank 🙏 Werde ich morgen ergänzen
